[project]
name = "modbus-hub"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pymodbustcp>=0.3.0",
    "pyside6>=6.10.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
